# Generated by Django 3.2.20 on 2023-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230727_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(),
        ),
    ]
